### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by localheinz** [theseer/phpunit#48]
* [x] `PHPUnit\Event\Bootstrap\Finished` (#5)

* [x] `PHPUnit\Event\TestSuite\Loaded` (#23)
* [x] `PHPUnit\Event\TestSuite\Sorted` (#26)
* [x] `PHPUnit\Event\TestSuite\Started` (#25)

  * [x] `PHPUnit\Event\Test\SkippedDueToUnsatisfiedRequirements` (#35)
  * [x] `PHPUnit\Event\Test\SkippedByDataProvider` (#33)

  * [x] `PHPUnit\Event\Test\BeforeFirstTestMethodCalled` (#44)
  * [x] `PHPUnit\Event\Test\BeforeFirstTestMethodFinished` (#11)
  * [x] `PHPUnit\Event\Test\BeforeTestMethodCalled` (#49)
  * [x] `PHPUnit\Event\Test\BeforeTestMethodFinished` (#54)

  * [x] `PHPUnit\Event\Test\PreConditionCalled` (#50)
  * [x] `PHPUnit\Event\Test\PreConditionFinished` (#42)

  * [x] `PHPUnit\Event\Test\Prepared` (#37)

  * [x] `PHPUnit\Event\Test\AbortedWithMessage` (#34)
  * [x] `PHPUnit\Event\Test\SkippedWithMessage` (#36)

    * [x] `PHPUnit\Event\TestDouble\TestStubCreated` (#51)
    * [x] `PHPUnit\Event\TestDouble\MockObjectCreated` (#15)
    * [x] `PHPUnit\Event\TestDouble\MockObjectCreatedFromWsdl` (#40)
    * [x] `PHPUnit\Event\TestDouble\MockObjectCreatedForAbstractClass` (#52)
    * [x] `PHPUnit\Event\TestDouble\MockObjectCreatedForTrait` (#16)
    * [x] `PHPUnit\Event\TestDouble\PartialMockObjectCreated` (#17)
    * [x] `PHPUnit\Event\TestDouble\TestProxyCreated` (#19)

    * [x] `PHPUnit\Event\Assertion\Made` (#4)

  * [x] `PHPUnit\Event\Test\Finished` (#30) -> ausführung der testmethode fertig

  * [x] `PHPUnit\Event\Test\PostConditionCalled` (#43) 
  * [x] `PHPUnit\Event\Test\PostConditionFinished` (#46)

  * [x] `PHPUnit\Event\Test\Passed` (#31)
  * [x] `PHPUnit\Event\Test\PassedWithWarning` (#47)
  * [x] `PHPUnit\Event\Test\PassedButRisky` (#32)
  * [x] `PHPUnit\Event\Test\Failed` (#29)
  * [x] `PHPUnit\Event\Test\Errored` (#28)

  * [x] `PHPUnit\Event\Test\AfterTestMethodCalled` (#53)
  * [x] `PHPUnit\Event\Test\AfterTestMethodFinished` (#20)
  * [x] `PHPUnit\Event\Test\AfterLastTestMethodCalled` (#45)
  * [x] `PHPUnit\Event\Test\AfterLastTestMethodFinished` (#10)

* [x] `PHPUnit\Event\TestSuite\Finished` (#24)

* [x] `PHPUnit\Event\GlobalState\Restored` (#9) 
* [x] `PHPUnit\Event\GlobalState\Modified` (#8) 
* [x] `PHPUnit\Event\GlobalState\Captured` (#7)

* [x] `PHPUnit\Event\Comparator\Registered` (#6)

* [x] `PHPUnit\Event\TestRunner\Finished` (#68)
