### ISSUE TITLE
Cleanup

### ISSUE THREAD

**Issue by localheinz** [theseer/phpunit#55]
- [x] add descriptions to `@internal annotations` (#56)
- [ ] import all classes in events (#57)
- [ ] fix wrapping (#58)
- [ ] move emitting of events to `TestResult` (and compose `TestFailure`) (#59)
- [x] remove `Application\Configured` event (#60)
- [ ] remove `Double` infix from method names in emitter (not from event classes) (#61)
- [x] rename `testSuiteRunFinished()` to `testSuiteFinished()` (#63)
- [x] fix co-authored-by comments in commits where necessary (#64)
